import {
  clampDayOfMonth,
  format,
  monthKey,
  monthsInRange,
  parseISO,
  type IsoDate,
  type MonthRange,
} from "./date";
import type { Entry, RecurringRule } from "@/db/schema";

/** A virtual entry generated by a rule, with no DB id. */
export type VirtualEntry = Omit<Entry, "id" | "createdAt"> & {
  id: null;
  createdAt: null;
  virtual: true;
};

/**
 * Expand a recurring rule across a month range into virtual entries.
 * The same month yields at most one entry. Day clamped to month length.
 */
export function expandRule(
  rule: RecurringRule,
  range: MonthRange
): VirtualEntry[] {
  if (!rule.active) return [];

  const startMonth = monthKey(rule.startsOn);
  const endMonth = rule.endsOn ? monthKey(rule.endsOn) : null;

  const months = monthsInRange(range).filter((mk) => {
    if (mk < startMonth) return false;
    if (endMonth && mk > endMonth) return false;
    return true;
  });

  return months.map((mk) => {
    const [y, m] = mk.split("-").map(Number);
    const day = clampDayOfMonth(y, m, rule.dayOfMonth);
    const occurredOn: IsoDate = format(new Date(y, m - 1, day), "yyyy-MM-dd");
    return {
      id: null,
      projectId: rule.projectId,
      type: rule.type,
      amountCents: rule.amountCents,
      currency: rule.currency,
      categoryId: rule.categoryId,
      occurredOn,
      note: rule.note,
      sourceRuleId: rule.id,
      createdAt: null,
      virtual: true,
    } satisfies VirtualEntry;
  });
}

function toInsert(ve: VirtualEntry): Omit<Entry, "id" | "createdAt"> {
  return {
    projectId: ve.projectId,
    type: ve.type,
    amountCents: ve.amountCents,
    currency: ve.currency,
    categoryId: ve.categoryId,
    occurredOn: ve.occurredOn,
    note: ve.note,
    sourceRuleId: ve.sourceRuleId,
  };
}

/**
 * FULL gap-fill: returns every (rule, month) the rule should have produced
 * between startsOn and (endsOn ?? untilDate) that doesn't yet exist.
 * Used by the explicit "Regenerate missing" action — will restore manually
 * deleted entries, which is the point.
 */
export function pendingMaterializations(
  rule: RecurringRule,
  existing: Pick<Entry, "occurredOn" | "sourceRuleId">[],
  untilDate: Date = new Date()
): Array<Omit<Entry, "id" | "createdAt">> {
  const startMonth = monthKey(rule.startsOn);
  const endBound = rule.endsOn
    ? monthKey(rule.endsOn)
    : monthKey(untilDate);
  const range: MonthRange = { from: startMonth, to: endBound };

  const existingKeys = new Set(
    existing
      .filter((e) => e.sourceRuleId === rule.id)
      .map((e) => monthKey(parseISO(e.occurredOn)))
  );

  return expandRule(rule, range)
    .filter((ve) => !existingKeys.has(monthKey(ve.occurredOn)))
    .map(toInsert);
}

/**
 * FORWARD-ONLY materialization: returns months strictly AFTER the latest
 * existing materialized entry for the rule (or from startsOn if none exist).
 * Respects manual deletions — won't resurrect entries the user deleted.
 * This is what the auto-materialize-on-dashboard-read uses.
 */
export function pendingForwardMaterializations(
  rule: RecurringRule,
  existing: Pick<Entry, "occurredOn" | "sourceRuleId">[],
  untilDate: Date = new Date()
): Array<Omit<Entry, "id" | "createdAt">> {
  const startMonth = monthKey(rule.startsOn);
  const endBound = rule.endsOn ? monthKey(rule.endsOn) : monthKey(untilDate);

  // Find the latest existing month for this rule.
  let latestMonth: string | null = null;
  for (const e of existing) {
    if (e.sourceRuleId !== rule.id) continue;
    const mk = monthKey(parseISO(e.occurredOn));
    if (latestMonth === null || mk > latestMonth) latestMonth = mk;
  }

  // Walk forward from the month AFTER latestMonth (or from startMonth if none).
  const from = latestMonth
    ? nextMonth(latestMonth) > startMonth
      ? nextMonth(latestMonth)
      : startMonth
    : startMonth;

  if (from > endBound) return [];

  const range: MonthRange = { from, to: endBound };
  return expandRule(rule, range).map(toInsert);
}

function nextMonth(mk: string): string {
  const [y, m] = mk.split("-").map(Number);
  const d = new Date(y, m, 1); // m is 1-indexed → date(year, m) is the next month
  return monthKey(d);
}
